workflows:
  web_to_apk:
    name: Build Web App as Android APK
    instance_type: mac_mini_m2
    environment:
      node: 20
      npm: 10
      java: 21
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build web app
        script: npm run build

      - name: Prepare Capacitor Android project
        script: |
          npx cap sync android

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
